name: tf
channels:
  - conda-forge
  - defaults
dependencies:
  - aiohappyeyeballs=2.6.1
  - aiohttp=3.12.14
  - aiosignal=1.4.0
  - alabaster=0.7.16
  - anyio=4.3.0
  - aom=3.8.1
  - argon2-cffi=23.1.0
  - argon2-cffi-bindings=21.2.0
  - arrow=1.3.0
  - astroid=3.3.11
  - asttokens=2.4.1
  - async-lru=2.0.4
  - async-timeout=5.0.1
  - asyncssh=2.21.0
  - atomicwrites=1.4.1
  - attrs=23.2.0
  - autopep8=2.0.4
  - babel=2.14.0
  - backports=1.0
  - backports.tarfile=1.2.0
  - bcrypt=4.3.0
  - beautifulsoup4=4.12.3
  - binaryornot=0.4.4
  - black=25.1.0
  - bleach=6.1.0
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2025.7.14
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cairo=1.18.0
  - certifi=2025.7.14
  - cffi=1.16.0
  - chardet=5.2.0
  - charset-normalizer=3.3.2
  - click=8.1.7
  - cloudpickle=3.0.0
  - colorama=0.4.6
  - comm=0.2.1
  - contourpy=1.2.0
  - cookiecutter=2.6.0
  - cryptography=45.0.5
  - cudatoolkit=11.2.2
  - cudnn=8.1.0.77
  - cycler=0.12.1
  - cytoolz=0.12.3
  - dask-core=2024.2.1
  - dav1d=1.2.1
  - debugpy=1.8.1
  - decorator=5.1.1
  - defusedxml=0.7.1
  - deprecated=1.2.18
  - diff-match-patch=20241021
  - dill=0.4.0
  - docstring-to-markdown=0.17
  - docutils=0.21.2
  - entrypoints=0.4
  - exceptiongroup=1.2.0
  - executing=2.0.1
  - expat=2.5.0
  - ffmpeg=6.1.1
  - flake8=7.1.2
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.49.0
  - fqdn=1.5.1
  - freeglut=3.2.2
  - freetype=2.12.1
  - frozenlist=1.7.0
  - fsspec=2024.2.0
  - fzf=0.64.0
  - gettext=0.21.1
  - glib=2.78.4
  - glib-tools=2.78.4
  - graphite2=1.3.13
  - gst-plugins-base=1.22.9
  - gstreamer=1.22.9
  - h11=0.14.0
  - h2=4.1.0
  - harfbuzz=8.3.0
  - hdf5=1.14.3
  - hpack=4.0.0
  - httpcore=1.0.3
  - httpx=0.26.0
  - hyperframe=6.0.1
  - icu=73.2
  - idna=3.6
  - imagecodecs-lite=2019.12.3
  - imageio=2.34.0
  - imagesize=1.4.1
  - importlib-metadata=7.0.1
  - importlib-resources=6.1.1
  - importlib_metadata=7.0.1
  - importlib_resources=6.1.1
  - imutils=0.5.4
  - inflection=0.5.1
  - intel-openmp=2024.0.0
  - intervaltree=3.1.0
  - ipykernel=6.29.5
  - ipython=8.18.1
  - isoduration=20.11.0
  - isort=6.0.1
  - jaraco.classes=3.4.0
  - jaraco.context=6.0.1
  - jaraco.functools=4.2.1
  - jasper=4.2.0
  - jedi=0.19.1
  - jellyfish=1.1.3
  - jinja2=3.1.3
  - joblib=1.4.2
  - json5=0.9.14
  - jsonpointer=2.4
  - jsonschema=4.21.1
  - jsonschema-specifications=2023.12.1
  - jsonschema-with-format-nongpl=4.21.1
  - jupyter-lsp=2.2.2
  - jupyter_client=8.6.0
  - jupyter_core=5.7.1
  - jupyter_events=0.9.0
  - jupyter_server=2.12.5
  - jupyter_server_terminals=0.5.2
  - jupyterlab=4.1.1
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.25.3
  - keyring=25.6.0
  - khronos-opencl-icd-loader=2023.04.17
  - kiwisolver=1.4.5
  - krb5=1.21.2
  - lazy_loader=0.3
  - lcms2=2.16
  - lerc=4.0.0
  - libabseil=20230802.1
  - libaec=1.1.2
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libclang13=15.0.7
  - libcurl=8.5.0
  - libdeflate=1.19
  - libexpat=2.5.0
  - libffi=3.4.2
  - libglib=2.78.4
  - libhwloc=2.9.3
  - libiconv=1.17
  - libjpeg-turbo=3.0.0
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libogg=1.3.4
  - libopencv=4.9.0
  - libopenvino=2023.3.0
  - libopenvino-auto-batch-plugin=2023.3.0
  - libopenvino-auto-plugin=2023.3.0
  - libopenvino-hetero-plugin=2023.3.0
  - libopenvino-intel-cpu-plugin=2023.3.0
  - libopenvino-intel-gpu-plugin=2023.3.0
  - libopenvino-ir-frontend=2023.3.0
  - libopenvino-onnx-frontend=2023.3.0
  - libopenvino-paddle-frontend=2023.3.0
  - libopenvino-pytorch-frontend=2023.3.0
  - libopenvino-tensorflow-frontend=2023.3.0
  - libopenvino-tensorflow-lite-frontend=2023.3.0
  - libopus=1.3.1
  - libpng=1.6.42
  - libprotobuf=4.25.1
  - libsodium=1.0.18
  - libspatialindex=2.1.0
  - libsqlite=3.45.1
  - libssh2=1.11.0
  - libtiff=4.6.0
  - libvorbis=1.3.7
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libxcb=1.15
  - libxml2=2.12.5
  - libzlib=1.2.13
  - locket=1.0.0
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gmp=6.1.0
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - markdown-it-py=3.0.0
  - markupsafe=2.1.5
  - matplotlib=3.8.3
  - matplotlib-base=3.8.3
  - matplotlib-inline=0.1.6
  - mccabe=0.7.0
  - mdurl=0.1.2
  - mistune=3.0.2
  - mkl=2024.0.0
  - more-itertools=10.7.0
  - msys2-conda-epoch=20160418
  - multidict=6.6.3
  - munkres=1.1.4
  - mypy_extensions=1.1.0
  - nbclient=0.8.0
  - nbconvert=7.16.1
  - nbconvert-core=7.16.1
  - nbconvert-pandoc=7.16.1
  - nbformat=5.9.2
  - nest-asyncio=1.6.0
  - networkx=3.2.1
  - notebook=7.1.0
  - notebook-shim=0.2.4
  - numpy=1.25.0
  - numpydoc=1.9.0
  - opencv=4.9.0
  - openh264=2.4.1
  - openjpeg=2.5.0
  - openssl=3.5.1
  - overrides=7.7.0
  - packaging=23.2
  - pandas=2.2.0
  - pandoc=3.7.0.2
  - pandocfilters=1.5.0
  - parso=0.8.3
  - partd=1.4.1
  - pathspec=0.12.1
  - pcre2=10.42
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=10.2.0
  - pip=24.0
  - pixman=0.43.2
  - pkgutil-resolve-name=1.3.10
  - platformdirs=4.2.0
  - pluggy=1.6.0
  - ply=3.11
  - prometheus_client=0.20.0
  - prompt-toolkit=3.0.42
  - propcache=0.3.1
  - psutil=5.9.8
  - pthread-stubs=0.4
  - pthreads-win32=2.9.1
  - ptyprocess=0.7.0
  - pugixml=1.14
  - pure_eval=0.2.2
  - py-opencv=4.9.0
  - pycodestyle=2.12.1
  - pyconify=0.2.1
  - pycparser=2.21
  - pydocstyle=6.3.0
  - pyflakes=3.2.0
  - pygithub=2.6.1
  - pygments=2.17.2
  - pyjwt=2.10.1
  - pylint=3.3.7
  - pylint-venv=3.0.4
  - pyls-spyder=0.4.0
  - pynacl=1.5.0
  - pyopenssl=25.1.0
  - pyparsing=3.1.1
  - pyqt=5.15.9
  - pyqt5-sip=12.12.2
  - pyqtwebengine=5.15.9
  - pysocks=1.7.1
  - python=3.9.18
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.19.1
  - python-gssapi=1.8.3
  - python-json-logger=2.0.7
  - python-lsp-black=2.0.0
  - python-lsp-jsonrpc=1.1.2
  - python-lsp-server=1.12.2
  - python-lsp-server-base=1.12.2
  - python-slugify=8.0.4
  - python-tzdata=2024.1
  - python_abi=3.9
  - pytoolconfig=1.2.5
  - pytz=2024.1
  - pyuca=1.2
  - pywavelets=1.4.1
  - pywin32=306
  - pywin32-ctypes=0.2.3
  - pywinpty=2.0.12
  - pyyaml=6.0.1
  - pyzmq=25.1.2
  - qdarkstyle=3.2.3
  - qstylizer=0.2.4
  - qt-main=5.15.8
  - qt-webengine=5.15.8
  - qtawesome=1.4.0
  - qtconsole=5.6.1
  - qtconsole-base=5.6.1
  - qtpy=2.4.3
  - referencing=0.33.0
  - requests=2.31.0
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rich=14.0.0
  - rope=1.14.0
  - rpds-py=0.18.0
  - rtree=1.4.0
  - scikit-image=0.20.0
  - scikit-learn=1.5.1
  - scipy=1.9.1
  - send2trash=1.8.2
  - setuptools=69.1.0
  - sip=6.7.12
  - six=1.16.0
  - snappy=1.1.10
  - sniffio=1.3.0
  - snowballstemmer=3.0.1
  - sortedcontainers=2.4.0
  - soupsieve=2.5
  - sphinx=7.4.7
  - sphinxcontrib-applehelp=2.0.0
  - sphinxcontrib-devhelp=2.0.0
  - sphinxcontrib-htmlhelp=2.1.0
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=2.0.0
  - sphinxcontrib-serializinghtml=1.1.10
  - spyder=6.0.7
  - spyder-base=6.0.7
  - spyder-kernels=3.0.5
  - stack_data=0.6.2
  - superqt=0.7.5
  - svt-av1=1.8.0
  - tbb=2021.11.0
  - terminado=0.18.0
  - text-unidecode=1.3
  - textdistance=4.6.3
  - threadpoolctl=3.5.0
  - three-merge=0.1.1
  - tifffile=2020.6.3
  - tinycss2=1.2.1
  - tk=8.6.13
  - toml=0.10.2
  - tomli=2.0.1
  - tomlkit=0.13.3
  - toolz=0.12.1
  - tornado=6.3.3
  - traitlets=5.14.3
  - types-python-dateutil=2.8.19.20240106
  - typing-extensions=4.9.0
  - typing_extensions=4.9.0
  - typing_utils=0.1.0
  - tzdata=2024a
  - ucrt=10.0.22621.0
  - ujson=5.10.0
  - unicodedata2=15.1.0
  - uri-template=1.3.0
  - urllib3=2.2.1
  - vc=14.3
  - vc14_runtime=14.44.35208
  - vs2015_runtime=14.44.35208
  - watchdog=6.0.0
  - wcwidth=0.2.13
  - webcolors=1.13
  - webencodings=0.5.1
  - websocket-client=1.7.0
  - whatthepatch=1.0.7
  - wheel=0.42.0
  - win_inet_pton=1.1.0
  - winpty=0.4.3
  - x264=1!164.3095
  - x265=3.5
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xz=5.2.6
  - yaml=0.2.5
  - yapf=0.43.0
  - yarl=1.20.1
  - zeromq=4.3.5
  - zipp=3.17.0
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - absl-py==2.1.0
      - astunparse==1.6.3
      - av==11.0.0
      - cachetools==5.3.2
      - flatbuffers==23.5.26
      - gast==0.4.0
      - google-auth==2.28.0
      - google-auth-oauthlib==0.4.6
      - google-pasta==0.2.0
      - grpcio==1.60.1
      - h5py==3.10.0
      - keras==2.10.0
      - keras-preprocessing==1.1.2
      - libclang==16.0.6
      - markdown==3.5.2
      - oauthlib==3.2.2
      - opt-einsum==3.3.0
      - protobuf==3.19.6
      - pyasn1==0.5.1
      - pyasn1-modules==0.3.0
      - requests-oauthlib==1.3.1
      - rsa==4.9
      - tensorboard==2.10.1
      - tensorboard-data-server==0.6.1
      - tensorboard-plugin-wit==1.8.1
      - tensorflow==2.10.1
      - tensorflow-addons==0.22.0
      - tensorflow-estimator==2.10.0
      - tensorflow-io-gcs-filesystem==0.31.0
      - termcolor==2.4.0
      - typeguard==2.13.3
      - werkzeug==3.0.1
      - wrapt==1.16.0
